import datetime
from uuid import uuid4

from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

def deserialize_user(user):
    """Deserialize user instance to JSON."""
    return {
        'id': user.id, 'username': user.username, 'email': user.email,
        'first_name': user.first_name, 'last_name': user.last_name
    }

def deserialize_date(date):
    """Deserialize user instance to JSON."""
    date_str = date
    dat = datetime.datetime.strptime(str(date_str)[:19], '%Y-%m-%d %H:%M:%S')
    dat =  str(dat.date())[8:] + ' ' + str(dat.date().strftime('%b')) + ' | ' + str(dat.time())[:5]
    return dat


class TrackableDateModel(models.Model):
    """Abstract model to Track the creation/updated date for a model."""

    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def _generate_unique_uri():
    """Generates a unique uri for the chat session."""
    return str(uuid4()).replace('-', '')[:15]


class ChatSession(TrackableDateModel):
    """ A Chat Session. The uri's are generated by taking the first 15 characters from a UUID """

    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    uri = models.URLField(default=_generate_unique_uri)
    title = models.CharField(max_length=50, default="", editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-update_date',)

class ChatSessionMessage(TrackableDateModel):
    """Store messages for a session."""

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    chat_session = models.ForeignKey(
        ChatSession, related_name='messages', on_delete=models.PROTECT
    )
    message = models.TextField(max_length=2000)
    status = models.IntegerField(default=0)

    def to_json(self):
        """deserialize message to JSON."""
        return {'user': deserialize_user(self.user), 'message': self.message,'status': self.status, 'create_date':deserialize_date(self.create_date)}
    
    class Meta:
        ordering = ('create_date',)

class ChatSessionMember(TrackableDateModel):
    """Store all users in a chat session."""

    chat_session = models.ForeignKey(
        ChatSession, related_name='members', on_delete=models.PROTECT
    )
    user = models.ForeignKey(User, on_delete=models.PROTECT)

