# Generated by Django 2.2.2 on 2019-07-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
