# Generated by Django 2.2.2 on 2019-07-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsessionmessage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ('-update_date',)},
        ),
    ]
