# Generated by Django 2.2.2 on 2019-07-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190702_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsessionmessage',
            options={'ordering': ('-create_date',)},
        ),
    ]
