# Generated by Django 2.2.2 on 2019-07-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190708_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsessionmessage',
            options={'ordering': ('create_date',)},
        ),
    ]
